-- ddl script for table rstation for postgresql
-- generated by (c) ispirer sqlways 9.0 build 6620 64bit licensed to ecom - william leung - united states - ispirer mnmtk 2020 microsoft sql server to postgresql database migration demo license (1 month, 20210626)
-- timestamp: mon may 31 14:30:26 2021
-- create table statement


drop table if exists rstation cascade;


create table rstation
(
   site_id decimal(4,0)  not null,
   statname varchar(5),
   r_id varchar(4),
   sz_id varchar(3),
   easting decimal(9,3),
   northing decimal(9,3),
   latitude decimal(10,7),
   longitude decimal(10,7),
   start_date timestamp,
   active varchar(1),
   show varchar(1),
   cmmview decimal(2,0),
   wcz_code decimal(3,0),
   wcsz_code decimal(3,0),
   riverid decimal(3,0),
   station_id decimal(3,0),
   valid_user varchar(10),
   valid_date timestamp,
   valid_code decimal(3,0),
   easting1 decimal(9,3),
   northing1 decimal(9,3),
   end_date timestamp,
   active_year numeric(18,0)
);


-- primary key

alter table rstation add constraint pk_rstation
primary key(site_id);

alter table rstation add constraint unique_statname
unique(statname);

alter table rstation add constraint fk_rstation_river
foreign key(r_id)
references river(r_id)   on delete no action  on update no action;


alter table rstation add constraint fk_rstation_wpco_sz
foreign key(sz_id)
references wpco_sz(sz_id)   on delete no action  on update no action;

