-- DDL script for indexes for table RSTATION for PostgreSQL
-- Generated by (c) Ispirer SQLWays 9.0 Build 6620 64bit Licensed to eCom - William Leung - United States - Ispirer MnMTK 2020 Microsoft SQL Server to PostgreSQL Database Migration Demo License (1 month, 20210626)
-- Timestamp: Mon May 31 14:30:26 2021
CREATE
INDEX IX_RSTATION_STATNAME
ON
RSTATION
(STATNAME ASC);

