-- DDL script for table TEN_ZONE for PostgreSQL
-- Generated by (c) Ispirer SQLWays 9.0 Build 6620 64bit Licensed to eCom - William Leung - United States - Ispirer MnMTK 2020 Microsoft SQL Server to PostgreSQL Database Migration Demo License (1 month, 20210626)
-- Timestamp: Mon May 31 14:43:53 2021
-- Create table statement


DROP TABLE IF EXISTS TEN_ZONE CASCADE;


CREATE TABLE TEN_ZONE
(
   ZONE_ID VARCHAR(1)   NOT NULL,
   ZONE_NAME VARCHAR(30),
   CHINESE_NAME VARCHAR(30),
   ZONE_ORDER DECIMAL(3,0),
   VALID_USER VARCHAR(10),
   VALID_DATE TIMESTAMP,
   VALID_CODE DECIMAL(3,0)
);


-- Primary key

ALTER TABLE TEN_ZONE add CONSTRAINT PK_TEN_ZONE
PRIMARY KEY(ZONE_ID);

