
DROP TABLE IF EXISTS TEN_ZONE CASCADE;
CREATE TABLE TEN_ZONE
(
   ZONE_ID VARCHAR(1)   NOT NULL,
   ZONE_NAME VARCHAR(30),
   CHINESE_NAME VARCHAR(30),
   ZONE_ORDER DECIMAL(3,0),
   VALID_USER VARCHAR(10),
   VALID_DATE TIMESTAMP,
   VALID_CODE DECIMAL(3,0)
);
ALTER TABLE TEN_ZONE add CONSTRAINT PK_TEN_ZONE PRIMARY KEY(ZONE_ID);



DROP TABLE IF EXISTS WPCO_WCZ CASCADE;
CREATE TABLE WPCO_WCZ
(
   WCZ_ID VARCHAR(2)   NOT NULL,
   ZONE_ID VARCHAR(1),
   WCZ_NAME VARCHAR(100),
   CHINESE_NAME VARCHAR(40),
   WCZ_LABEL VARCHAR(4),
   WCZ_ABBR VARCHAR(10),
   FAD TIMESTAMP,
   WCZ_CODE DECIMAL(2,0),
   VALID_USER VARCHAR(10),
   VALID_DATE TIMESTAMP,
   VALID_CODE DECIMAL(3,0)
);
ALTER TABLE WPCO_WCZ add CONSTRAINT PK_WPCO_WCZ PRIMARY KEY(WCZ_ID);
ALTER TABLE WPCO_WCZ add CONSTRAINT FK_WPCO_WCZ_TEN_ZONE FOREIGN KEY(ZONE_ID)
	REFERENCES TEN_ZONE(ZONE_ID)   ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS WPCO_SZ CASCADE;
CREATE TABLE WPCO_SZ
(
   SZ_ID VARCHAR(3)   NOT NULL,
   WCZ_ID VARCHAR(2)   NOT NULL,
   SZ_NAME VARCHAR(100),
   CHINESE_NAME VARCHAR(60),
   MARINE_INLAND VARCHAR(1),
   WPCO_SUBLEG VARCHAR(2),
   WCSZ_CODE DECIMAL(2,0),
   VALID_USER VARCHAR(10),
   VALID_DATE TIMESTAMP,
   VALID_CODE DECIMAL(3,0)
);
ALTER TABLE WPCO_SZ add CONSTRAINT PK_WPCO_SZ PRIMARY KEY(SZ_ID);
ALTER TABLE WPCO_SZ add CONSTRAINT FK_WPCO_SZ_WPCO_WCZ FOREIGN KEY(WCZ_ID)
	REFERENCES WPCO_WCZ(WCZ_ID)   ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS RIVER CASCADE;
CREATE TABLE river (
	r_id varchar(4) NOT NULL,
	zone_id varchar(1) NOT NULL,
	river_name varchar(50) NULL,
	chinese_name varchar(20) NULL,
	river_id numeric(5) NULL,
	valid_user varchar(10) NULL,
	valid_date timestamp NULL,
	valid_code numeric(3) NULL,
	CONSTRAINT pk_river PRIMARY KEY (r_id)
);
ALTER TABLE public.river ADD CONSTRAINT fk_river_ten_zone FOREIGN KEY (zone_id) REFERENCES ten_zone(zone_id);




drop table if exists rstation cascade;
CREATE TABLE rstation (
	site_id numeric(4) NOT NULL,
	statname varchar(5) NULL,
	r_id varchar(4) NULL,
	sz_id varchar(3) NULL,
	easting numeric(9, 3) NULL,
	northing numeric(9, 3) NULL,
	latitude numeric(10, 7) NULL,
	longitude numeric(10, 7) NULL,
	start_date timestamp NULL,
	active varchar(1) NULL,
	"show" varchar(1) NULL,
	cmmview numeric(2) NULL,
	wcz_code numeric(3) NULL,
	wcsz_code numeric(3) NULL,
	riverid numeric(3) NULL,
	station_id numeric(3) NULL,
	valid_user varchar(10) NULL,
	valid_date timestamp NULL,
	valid_code numeric(3) NULL,
	easting1 numeric(9, 3) NULL,
	northing1 numeric(9, 3) NULL,
	end_date timestamp NULL,
	active_year numeric(18) NULL,
	CONSTRAINT pk_rstation PRIMARY KEY (site_id),
	CONSTRAINT uk_qxcf1srd9fuufjcm81mc3km2q UNIQUE (statname)
);
CREATE INDEX ix_rstation_statname ON public.rstation USING btree (statname);
ALTER TABLE public.rstation ADD CONSTRAINT fk_rstation_river FOREIGN KEY (r_id) REFERENCES river(r_id);
ALTER TABLE public.rstation ADD CONSTRAINT fk_rstation_wpco_sz FOREIGN KEY (sz_id) REFERENCES wpco_sz(sz_id);





drop table if exists mstation cascade;
create table mstation
(
   site_id decimal(4,0)  not null,
   mw_name varchar(10),
   ms_name varchar(10),
   mw_ts_name varchar(10),
   ms_ts_name varchar(10),
   ms_dx_name varchar(10),
   hs_name varchar(10),
   mt_name varchar(10),
   depth decimal(3,0),
   sz_id varchar(3),
   easting decimal(9,3),
   northing decimal(9,3),
   latitude decimal(10,7),
   longitude decimal(10,7),
   environment varchar(50),
   start_date timestamp,
   active varchar(1),
   show varchar(1),
   cmmview decimal(2,0),
   wcz_code decimal(3,0),
   mw_id decimal(3,0),
   ms_id decimal(3,0),
   station_id decimal(3,0),
   valid_user varchar(10),
   valid_date timestamp,
   valid_code decimal(3,0),
   easting1 decimal(9,3),
   northing1 decimal(9,3)
);
alter table mstation add constraint pk_mstation primary key(site_id);
alter table mstation add constraint fk_mstation_wpco_sz foreign key(sz_id)
	references wpco_sz(sz_id)   on delete no action  on update no action;
CREATE UNIQUE INDEX unique_mw_name ON mstation(mw_name);




DROP TABLE IF EXISTS BM_BEACH CASCADE;
CREATE TABLE BM_BEACH
(
   SITE_ID DECIMAL(4,0)  NOT NULL,
   BEACH_CODE VARCHAR(5)   NOT NULL,
   BEACH_NAME VARCHAR(52)   NOT NULL,
   CHINESE_NAME VARCHAR(24),
   SC_NAME VARCHAR(24),
   DISTRICT_CODE VARCHAR(3)   NOT NULL,
   RAIN_STATION_CODE VARCHAR(3)   NOT NULL,
   TIDE_STATION_CODE VARCHAR(3)   NOT NULL,
   REMARK VARCHAR(1000),
   SZ_ID VARCHAR(3),
   EASTING DECIMAL(9,3),
   NORTHING DECIMAL(9,3),
   LATITUDE DECIMAL(10,7),
   LONGITUDE DECIMAL(10,7),
   WCZ_CODE DECIMAL(3,0),
   VALID_USER VARCHAR(10),
   VALID_DATE TIMESTAMP,
   VALID_CODE DECIMAL(3,0)
);
ALTER TABLE BM_BEACH add CONSTRAINT PK_BEACH PRIMARY KEY(BEACH_CODE);
ALTER TABLE BM_BEACH add CONSTRAINT PK_BEACH_ID UNIQUE(SITE_ID);




DROP TABLE IF EXISTS bm_beach_ec_agm_rank_report CASCADE;
create table bm_beach_ec_agm_rank_report (
      district_name varchar(50),
      district_name_c varchar(50),
      hotline_district varchar(20),
      hotline_district_c varchar(10),
      beach_name varchar(52) not null,
      chinese_name varchar(24),
      sc_name varchar(24),
      beach_group varchar(2),
      district_order varchar(3),
      beach_code varchar(5),
      year_ int,
      annual_log_g_mean decimal(38,8),
      annual_g_mean decimal(38,8),
      sample_count int,
      rank_ decimal(2,0),
      list_order_2 varchar(3),
      constraint pk_bm_beach_ec_agm_rank_report primary key (beach_code, year_)
);
ALTER TABLE bm_beach_ec_agm_rank_report add CONSTRAINT fk_bm_beach_ec_agm_rank_report FOREIGN KEY(beach_code)
	REFERENCES bm_beach(beach_code)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS bm_visit_label_summary CASCADE;
create table bm_visit_label_summary (
	district_name varchar(45),
	beach_name varchar(52),
	beach_group varchar(2),
	closed varchar(1),
	district_order varchar(3),
	list_order varchar(3),
	bmvisit_id varchar(14) not null,
	site_id decimal(4,0),
	mdate timestamp not null,
	stime decimal(4,0),
	sample_no decimal(2,0),
	beach_code varchar(5),
	sample_date timestamp,
	sample_time varchar(5),
	temper decimal(3,1),
	do_ decimal(4,2),
	dos decimal(4,1),
	sal decimal(4,2),
	sal_r decimal(38,2),
	sal_m decimal(38,2),
	sal_l decimal(38,2), 
	sal_o decimal(38,2),
	ph decimal(4,2),
	turb decimal(6,2),
	weather_value decimal(1,0),
	wind_value decimal(1,0),
	climate_value decimal(1,0),
	sea_clarity_value decimal(1,0),
	sea_condition_value decimal(1,0),
	wind_direction varchar(3),
	bather_value decimal(1,0),
	tide_value decimal(1,0),
	tide_ratio decimal(5,2),
	tide_height decimal(5,2),
	abs_tide_height decimal(5,2),
	ec_r decimal(38,0),
	ec_m decimal(38,0),
	ec_l decimal(38,0),
	ec_o decimal(38,0),
	ec_s1 decimal(38,0),
	ec_s2 decimal(38,0),
	ec_s3 decimal(38,0),
	ec_s4 decimal(38,0),
	ec_s5 decimal(38,0),
	sal_s1 decimal(38,2),
	sal_s2 decimal(38,2),
	sal_s3 decimal(38,2),
	sal_s4 decimal(38,2),
	sal_s5 decimal(38,2),
	sal_s1_2 decimal(38,2),
	sal_s2_2 decimal(38,2),
	sal_s3_2 decimal(38,2),
	sal_s4_2 decimal(38,2),
	sal_s5_2 decimal(38,2),
	sal_f1_2 decimal(38,2),
	sal_f2_2 decimal(38,2),
	sal_f3_2 decimal(38,2),
	sal_f4_2 decimal(38,2),
	sal_f5_2 decimal(38,2),
	flow_s1 varchar(2),
	flow_s2 varchar(2),
	flow_s3 varchar(2),
	flow_s4 varchar(2),
	flow_s5 varchar(2),
	flow_f1 varchar(2),
	flow_f2 varchar(2),
	flow_f3 varchar(2),
	flow_f4 varchar(2),
	flow_f5 varchar(2),
	ec_f1 decimal(38,0),
	ec_f2 decimal(38,0),
	ec_f3 decimal(38,0),
	ec_f4 decimal(38,0),
	ec_f5 decimal(38,0),
	fc_r decimal(38,0),
	fc_m decimal(38,0),
	fc_l decimal(38,0),
	fc_o decimal(38,0),
	fc_s1 decimal(38,0),
	fc_s2 decimal(38,0),
	fc_s3 decimal(38,0),
	fc_s4 decimal(38,0),
	fc_s5 decimal(38,0),
	fc_f1 decimal(38,0),
	fc_f2 decimal(38,0),
	fc_f3 decimal(38,0),
	fc_f4 decimal(38,0),
	fc_f5 decimal(38,0),
	g_mean decimal(9,0),
	r_g_mean decimal(9,0),
	log_g_mean decimal(12,8),
	adj_log_gm decimal(12,8),
	mth_g_mean decimal(9,0),
	wk_g_mean decimal(9,0),
	g_mean_fc decimal(9,0),
	r_g_mean_fc decimal(9,0),
	log_g_mean_fc decimal(12,8),
	adj_log_gm_fc decimal(12,8),
	mth_g_mean_fc decimal(9,0),
	wk_g_mean_fc decimal(9,0),
	move_avg decimal(12,8),
	move_avg_fc decimal(12,8),
	grade decimal(2,0),
	grade_change decimal(1,0),
	remarks varchar(200),
	dayappend timestamp,
	dayedit timestamp,
	dayupload timestamp,
	rain_station_code varchar(3),
	sdatetime timestamp,
	rainfall decimal(5,1),
	rainfall_max_3hr decimal(5,1),
	rainfall_max_time timestamp,
	rainfall_last_12hr decimal(5,1),
	rainfall_last_24hr decimal(5,1),
	rainfall_last_72hr decimal(5,1),
	risk_rain_max_3hr varchar(1),
	risk_rain_last_12hr varchar(1),
	risk_rain_last_24hr varchar(1),
	risk_rain_last_72hr varchar(1),
	weather varchar(20),
	wind varchar(20),
	climate varchar(20),
	sea_clarity varchar(20),
	sea_condition varchar(20),
	bather varchar(20),
	tide varchar(20),
	flow_label_s1 varchar(20),
	flow_label_s2 varchar(20),
	flow_label_s3 varchar(20),
	flow_label_s4 varchar(20),
	flow_label_s5 varchar(20),
	flow_label_f1 varchar(20),
	flow_label_f2 varchar(20),
	flow_label_f3 varchar(20),
	flow_label_f4 varchar(20),
	flow_label_f5 varchar(20),
	tide_station_code varchar(3),
	mrefuse_cleanlines_level decimal(1,0),
	constraint pk_bm_visit_label_summary primary key (bmvisit_id)
);
ALTER TABLE bm_visit_label_summary add CONSTRAINT fk_bm_visit_label_summary FOREIGN KEY(beach_code)
	REFERENCES bm_beach(beach_code)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS marine_water1 CASCADE;
create table marine_water1
   (
      zone_ varchar(30),
      wcz varchar(10),
      subzone varchar(100),
      station varchar(10),
      mdate timestamp not null,
      stime decimal(4,0),
      sam_no decimal(4,0),
      d_code varchar(30),
      temper decimal(38,6),
      ph_sc decimal(38,6),
      sal decimal(38,6),
      cond decimal(38,6),
      do_ decimal(38,6),
      do_sat decimal(38,6),
      flscufa decimal(38,6),
      turb_sc decimal(38,6),
      par decimal(38,15),
      l_bod5 varchar(30),
      bod5 decimal(38,6),
      l_fc varchar(30),
      fc double precision,
      l_ecoli varchar(30),
      ecoli double precision,
	  l_ph_m varchar(30),
	  ph_m decimal(17,6),
	  l_turb_m varchar(30),
	  turb_m decimal(17,6),
      l_nh4 varchar(30),
      nh4 decimal(38,6),
      l_no2 varchar(30),
      no2 decimal(38,6),
      l_no3 varchar(30),
      no3 decimal(38,6),
      l_tkn_s varchar(30),
      tkn_s decimal(38,6),
      l_tkn_p varchar(30),
      tkn_p decimal(38,6),
      l_tkn_sp varchar(30),
      tkn_sp decimal(38,6),
      l_po4 varchar(30),
      po4 decimal(38,6),
      l_tp_s varchar(30),
      tp_s decimal(38,6),
      l_tp_p varchar(30),
      tp_p decimal(38,6),
      l_tp_sp varchar(30),
      tp_sp decimal(38,6),
      l_sio2 varchar(30),
      sio2 decimal(38,6),
      l_ss varchar(30),
      ss decimal(38,6),
      l_tvs varchar(30),
      tvs decimal(38,6),
      l_chl varchar(30),
      chl decimal(38,6),
      l_phae varchar(30),
      phae decimal(38,6),
	  tin decimal(17,6),
	  tn decimal(17,6),
      nh3 decimal(17,8),
      sol_rad decimal(6,2),
      air_temp decimal(4,2),
      wind_sp decimal(3,1),
      wind_dir decimal(4,1),
      sea_cond varchar(20),
      sea_col varchar(11),
      fish_kill varchar(1),
      sd decimal(3,1),
      weather varchar(20),
	  nh4_nm decimal(38,11),
	  no2_nm decimal(38,11),
	  no3_nm decimal(38,11),
	  tkn_nm decimal(38,11),
	  nox_nm decimal(38,11),
	  tin_nm decimal(38,11),
	  tn_nm decimal(38,11),
	  po4_pm decimal(38,11),
	  tp_pm decimal(38,11),
	  tin_po4_mmr decimal(38,14),
	  tn_tp_mmr decimal(38,14),
	  view_no decimal(2,0),
	  
      constraint pk_marine_water1 primary key (station,mdate,d_code)
   );
ALTER TABLE marine_water1 add CONSTRAINT fk_marine_water1 FOREIGN KEY(station)
	REFERENCES mstation(mw_name)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS marine_water2 CASCADE;
create table marine_water2
   (
      zone_ varchar(30),
      wcz varchar(10),
      subzone varchar(100),
      station varchar(10),
      mdate timestamp not null,
      stime decimal(4,0),
      sam_no decimal(4,0),
      d_code varchar(30),
      temper decimal(38,6),
      ph_sc decimal(38,6),
      sal decimal(38,6),
      cond decimal(38,6),
      do_ decimal(38,6),
      do_sat decimal(38,6),
      flscufa decimal(38,6),
      turb_sc decimal(38,6),
      par decimal(38,15),
      l_bod5 varchar(30),
      bod5 decimal(38,6),
      l_fc varchar(30),
      fc double precision,
      l_ecoli varchar(30),
      ecoli double precision,
      l_nh4 varchar(30),
      nh4 decimal(38,6),
      l_no2 varchar(30),
      no2 decimal(38,6),
      l_no3 varchar(30),
      no3 decimal(38,6),
      l_tkn_s varchar(30),
      tkn_s decimal(38,6),
      l_tkn_p varchar(30),
      tkn_p decimal(38,6),
      l_tkn_sp varchar(30),
      tkn_sp decimal(38,6),
      l_po4 varchar(30),
      po4 decimal(38,6),
      l_tp_s varchar(30),
      tp_s decimal(38,6),
      l_tp_p varchar(30),
      tp_p decimal(38,6),
      l_tp_sp varchar(30),
      tp_sp decimal(38,6),
      l_sio2 varchar(30),
      sio2 decimal(38,6),
      l_ss varchar(30),
      ss decimal(38,6),
      l_tvs varchar(30),
      tvs decimal(38,6),
      l_chl varchar(30),
      chl decimal(38,6),
      l_phae varchar(30),
      phae decimal(38,6),
      sol_rad decimal(6,2),
      air_temp decimal(4,2),
      wind_sp decimal(3,1),
      wind_dir decimal(4,1),
      sea_cond varchar(20),
      sea_col varchar(11),
      fish_kill varchar(1),
      sd decimal(3,1),
      weather varchar(20),
      nh3 decimal(38,8),
      tin decimal(38,6),
      tn decimal(38,6),
      constraint pk_marine_water2 primary key (station,mdate,d_code)
   );
ALTER TABLE marine_water2 add CONSTRAINT fk_marine_water2 FOREIGN KEY(station)
	REFERENCES mstation(mw_name)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS marine_water_wqo_raw1 CASCADE;
create table marine_water_wqo_raw1
   (
      zone_ varchar(30),
      wcz varchar(10),
      subzone varchar(100),
      station varchar(10),
      mdate timestamp not null,
      stime decimal(4,0),
      sample_no decimal(4,0),
	  
	  dos decimal(7,3),
	  dom decimal(7,3),
	  dob decimal(7,3),
	  doc decimal(38,6),
	  doa decimal(38,6),
	  tin decimal(38,6),
      nh3 decimal(38,8),
	  ecoli double precision,
	  min_dos decimal(2,1),
	  min_dos_pc decimal(3,0),
	  min_dom decimal(2,1),
	  min_dom_pc decimal(3,0),
	  min_dob decimal(2,1),
	  min_dob_pc decimal(3,0),
	  min_doc decimal(2,1),
	  min_doc_pc decimal(3,0),
	  min_doa decimal(2,1),
	  min_doa_pc decimal(3,0),
	  max_tin_aam decimal(2,1),
	  max_nh3_aam decimal(4,3),
	  max_ecoli_agm decimal(4,0),
	  meet_dos varchar(3),
	  meet_dom varchar(3),
	  meet_dob varchar(3),
	  meet_doc varchar(3),
	  meet_doa varchar(3),
	  
      constraint pk_marine_water_wqo_raw1 primary key (station,mdate)
   );
ALTER TABLE marine_water_wqo_raw1 add CONSTRAINT fk_marine_water_wqo_raw1 FOREIGN KEY(station)
	REFERENCES mstation(mw_name)  ON DELETE NO ACTION  ON UPDATE NO ACTION;



   
DROP TABLE IF EXISTS river_water1 CASCADE;
create table river_water1(
	zone varchar(30),
	wcz varchar(10),
	subzone varchar(100),
	river varchar(50),
	station varchar(5),
	mdate timestamp not null,
	stime decimal(4,0),
	sample_no smallint,
	l_sal varchar(1),
	sal decimal(4,2),
	l_cond varchar(1),
	cond decimal(7,2),
	l_do varchar(1),
	do_ decimal(4,2),
	l_dos varchar(1),
	dos decimal(4,1),
	l_ph varchar(1),
	ph decimal(4,2),
	temper dec(3,1),
	l_ss varchar(1),
	ss decimal(7,2),
	l_ts varchar(1),
	ts decimal(5,0),
	l_tvs varchar(1),
	tvs decimal(6,1),
	l_turb varchar(1),
	turb decimal(6,2),
	l_bod5 varchar(1),
	bod5 decimal(6,2),
	l_cod varchar(1),
	cod decimal(7,2),
	l_toc varchar(1),
	toc decimal(5,0),
	l_oil varchar(1),
	oil decimal(4,1),
	l_ec varchar(1),
	ec decimal(9,0),
	l_fc varchar(1),
	fc decimal(9,0),
	l_nh4 varchar(1),
	nh4 decimal(6,3),
	l_no2 varchar(1),
	no2 decimal(5,3),
	l_no3 varchar(1),
	no3 decimal(6,3),
	l_tkns varchar(1),
	tkns decimal(5,2),
	l_tknsp varchar(1),
	tknsp decimal(6,2),
	l_po4 varchar(1),
	po4 decimal(5,3),
	l_tps varchar(1),
	tps decimal(4,2),
	l_tpsp varchar(1),
	tpsp decimal(5,2),
	l_sil varchar(1),
	sil decimal(5,2),
	l_tcyn varchar(1),
	tcyn decimal(4,2),
	l_deterg varchar(1),
	deterg decimal(4,2),
	l_fl varchar(1),
	fl decimal(5,1),
	l_cl varchar(1),
	cl decimal(6,0),
	l_h2s varchar(1),
	h2s decimal(3,2),
	l_sulp varchar(1),
	sulp decimal(4,2),
	l_ssp varchar(1),
	ssp decimal(4,2),
	l_chl varchar(1),
	chl decimal(4,1),
	l_pheo varchar(1),
	pheo decimal(4,1),
	l_al varchar(1),
	al decimal(7,1),
	l_sb varchar(1),
	sb decimal(3,0),
	l_arsenic varchar(1),
	arsenic decimal(6,1),
	l_ba varchar(1),
	ba decimal(4,0),
	l_be varchar(1),
	be decimal(3,0),
	l_b varchar(1),
	b decimal(5,1),
	l_cd varchar(1),
	cd decimal(5,1),
	l_cr varchar(1),
	cr decimal(6,1),
	l_cu varchar(1),
	cu decimal(6,1),
	l_fe varchar(1),
	fe decimal(7,1),
	l_pb varchar(1),
	pb decimal(7,2),
	l_mn varchar(1),
	mn decimal(5,0),
	l_hg varchar(1),
	hg decimal(4,1),
	l_mo varchar(1),
	mo decimal(3,0),
	l_ni varchar(1),
	ni decimal(5,1),
	l_ag varchar(1),
	ag decimal(3,0),
	l_tl varchar(1),
	tl decimal(3,0),
	l_v varchar(1),
	v decimal(3,0),
	l_zn varchar(1),
	zn decimal(6,1),
	depth decimal(38,6),
	width decimal(38,2),
	vel decimal(38,6),
	flow decimal(38,6),
	bod5_pt decimal(1,0),
	nh4_pt decimal(1,0),
	dos_pt decimal(1,0),
	wqi_pt decimal(3,0),
	wqi_grade varchar(10),
	l_nh3 varchar(1),
	nh3 decimal(22,8),
	tin decimal(8,3),
	tn decimal(9,3),
	weather varchar(10),
	color varchar(10),
	smell varchar(1),
	rainfall varchar(10),
	tide varchar(10),
	remark varchar(500),
	constraint pk_river_water1 primary key (station,mdate)
);
ALTER TABLE river_water1 add CONSTRAINT fk_river_water1 FOREIGN KEY(station)
	REFERENCES rstation(statname)  ON DELETE NO ACTION  ON UPDATE NO ACTION;





DROP TABLE IF EXISTS river_water2 CASCADE;
create table river_water2(
	zone varchar(30),
	wcz varchar(10),
	subzone varchar(100),
	river varchar(50),
	station varchar(5),
	mdate timestamp not null,
	stime decimal(4,0),
	sample_no smallint,
	l_sal varchar(1),
	sal decimal(4,2),
	l_cond varchar(1),
	cond decimal(7,2),
	l_do varchar(1),
	do_ decimal(4,2),
	l_dos varchar(1),
	dos decimal(4,1),
	l_ph varchar(1),
	ph decimal(4,2),
	temper dec(3,1),
	l_ss varchar(1),
	ss decimal(7,2),
	l_ts varchar(1),
	ts decimal(5,0),
	l_tvs varchar(1),
	tvs decimal(6,1),
	l_turb varchar(1),
	turb decimal(6,2),
	l_bod5 varchar(1),
	bod5 decimal(6,2),
	l_cod varchar(1),
	cod decimal(7,2),
	l_toc varchar(1),
	toc decimal(5,0),
	l_oil varchar(1),
	oil decimal(4,1),
	l_ec varchar(1),
	ec decimal(9,0),
	l_fc varchar(1),
	fc decimal(9,0),
	l_nh4 varchar(1),
	nh4 decimal(6,3),
	l_no2 varchar(1),
	no2 decimal(5,3),
	l_no3 varchar(1),
	no3 decimal(6,3),
	l_tkns varchar(1),
	tkns decimal(5,2),
	l_tknsp varchar(1),
	tknsp decimal(6,2),
	l_po4 varchar(1),
	po4 decimal(5,3),
	l_tps varchar(1),
	tps decimal(4,2),
	l_tpsp varchar(1),
	tpsp decimal(5,2),
	l_sil varchar(1),
	sil decimal(5,2),
	l_tcyn varchar(1),
	tcyn decimal(4,2),
	l_deterg varchar(1),
	deterg decimal(4,2),
	l_fl varchar(1),
	fl decimal(5,1),
	l_cl varchar(1),
	cl decimal(6,0),
	l_h2s varchar(1),
	h2s decimal(3,2),
	l_sulp varchar(1),
	sulp decimal(4,2),
	l_ssp varchar(1),
	ssp decimal(4,2),
	l_chl varchar(1),
	chl decimal(4,1),
	l_pheo varchar(1),
	pheo decimal(4,1),
	l_al varchar(1),
	al decimal(7,1),
	l_sb varchar(1),
	sb decimal(3,0),
	l_arsenic varchar(1),
	arsenic decimal(6,1),
	l_ba varchar(1),
	ba decimal(4,0),
	l_be varchar(1),
	be decimal(3,0),
	l_b varchar(1),
	b decimal(5,1),
	l_cd varchar(1),
	cd decimal(5,1),
	l_cr varchar(1),
	cr decimal(6,1),
	l_cu varchar(1),
	cu decimal(6,1),
	l_fe varchar(1),
	fe decimal(7,1),
	l_pb varchar(1),
	pb decimal(7,2),
	l_mn varchar(1),
	mn decimal(5,0),
	l_hg varchar(1),
	hg decimal(4,1),
	l_mo varchar(1),
	mo decimal(3,0),
	l_ni varchar(1),
	ni decimal(5,1),
	l_ag varchar(1),
	ag decimal(3,0),
	l_tl varchar(1),
	tl decimal(3,0),
	l_v varchar(1),
	v decimal(3,0),
	l_zn varchar(1),
	zn decimal(6,1),
	depth decimal(38,6),
	width decimal(38,2),
	vel decimal(38,6),
	flow decimal(38,6),
	bod5_pt decimal(1,0),
	nh4_pt decimal(1,0),
	dos_pt decimal(1,0),
	wqi_pt decimal(3,0),
	wqi_grade varchar(10),
	l_nh3 varchar(1),
	nh3 decimal(22,8),
	tin decimal(8,3),
	tn decimal(9,3),
	weather varchar(10),
	color varchar(10),
	smell varchar(1),
	rainfall varchar(10),
	tide varchar(10),
	remark varchar(500),
	constraint pk_river_water2 primary key (station,mdate)
);
ALTER TABLE river_water2 add CONSTRAINT fk_river_water2 FOREIGN KEY(station)
	REFERENCES rstation(statname)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




DROP TABLE IF EXISTS river_water_wqi1 CASCADE;
create table river_water_wqi1(
	zone varchar(30),
	wcz varchar(10),
	subzone varchar(100),
	river varchar(100),
	station varchar(5),
	mdate timestamp not null,
	stime decimal(4,0),
	sample_no decimal(2,0),
	l_bod5 varchar(1),
	bod5 decimal(22,6),
	l_nh4 varchar(1),
	nh4 decimal(22,6),
	l_dos varchar(1),
	dos decimal(22,6),
	bod5_pt decimal(1,0),
	nh4_pt decimal(1,0),
	dos_pt decimal(1,0),
	wqi_pt decimal(3,0),
	wqi_grade varchar(10),
	view_no decimal(2,0),
	constraint pk_river_water_wqi1 primary key (station,mdate)
);
ALTER TABLE river_water_wqi1 add CONSTRAINT fk_river_water_wqi1 FOREIGN KEY(station)
	REFERENCES rstation(statname)  ON DELETE NO ACTION  ON UPDATE NO ACTION;





drop table if exists river_water_wqo_sum0 cascade;
create table river_water_wqo_sum0 (
	zone_ varchar(30),
	wcz varchar(10),
	subzone varchar(100),
	river varchar(50),
	station varchar(5),
	yr int,
	total int,
	min_ph decimal(2,1),
	max_ph decimal(2,1),
	n_ph int,
	m_ph int,
	rate_ph numeric(27,13),
	n_bod5 int,
	max_bod5 decimal(3,1),
	m_bod5 int,
	rate_bod5 numeric(27,13),
	max_cod decimal(3,1),
	n_cod int,
	m_cod int,
	rate_cod numeric(27,13),
	min_do decimal(2,1),
	n_do int,
	m_do int,
	rate_do numeric(27,13),
	max_amd_ss decimal(3,1),
	n_ss int,
	amd_ss decimal(38,6),
	rate_ss_amd int,
	max_nh4 decimal(2,1),
	n_nh4 int,
	m_nh4 int,
	rate_nh4 numeric(27,13),
	max_aam_nh3 decimal(4,3),
	nh3_aam decimal(38,8),
	rate_nh3_aam int,
	max_5md_ec decimal(4,0),
	n_ec_5md int,
	m_ec_5md int,
	rate_ec_5md numeric(27,13),
	max_5gm_ec decimal(4,0),
	n_ec_5gm int,
	m_ec_5gm int,
	rate_ec_5gm numeric(27,13),
	max_agm_ec decimal(4,0),
	ec_agm DOUBLE PRECISION,
	rate_ec_agm int,
	rate_4wqo numeric(33,15),
	rate_5wqo numeric(33,15),
	constraint pk_river_water_wqo_sum0 primary key (station,yr)
);
ALTER TABLE river_water_wqo_sum0 add CONSTRAINT fk_river_water_wqo_sum0 FOREIGN KEY(station)
	REFERENCES rstation(statname)  ON DELETE NO ACTION  ON UPDATE NO ACTION;




drop table if exists rw_wqi_avg cascade;
create table rw_wqi_avg (
	site_id decimal(4,0),
	yr int,
	total int,
	bod5_pt_avg decimal(38,6),
	nh4_pt_avg decimal(38,6),
	dos_pt_avg decimal(38,6),
	wqi_pt_avg decimal(38,6),
	wqi_grade_avg varchar(10),
	constraint pk_rw_wqi_avg primary key (site_id,yr)
);
alter table rw_wqi_avg add constraint fk_rw_wqi_avg foreign key(site_id)
	references rstation(site_id)  on delete no action  on update no action;

  
